package com.importre.kotlin.enumerize;

import com.google.common.base.Joiner;
import com.google.common.io.Files;
import com.google.testing.compile.JavaFileObjects;
import com.squareup.kotlinpoet.AnnotationSpec;
import com.squareup.kotlinpoet.FileSpec;
import com.squareup.kotlinpoet.FunSpec;
import com.squareup.kotlinpoet.PropertySpec;
import com.squareup.kotlinpoet.TypeNames;
import com.squareup.kotlinpoet.TypeVariableName;

import org.intellij.lang.annotations.Language;
import org.jetbrains.annotations.NotNull;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;

import javax.tools.JavaFileObject;

import kotlin.jvm.JvmName;

import static com.google.common.truth.Truth.assertThat;
import static com.google.testing.compile.Compiler.javac;

public class EnumExtTest {

    @Test
    public void testGenerateFile() throws IOException {

        JavaFileObject sourceObject = getSourceObject();
        File tempDir = new File(System.getProperty("java.io.tmpdir"));
        File file = new File(tempDir, "test/LogExt.kt");

        javac()
            .withOptions("-Akapt.kotlin.generated=" + tempDir)
            .withProcessors(new EnumExtProcessor())
            .compile(sourceObject)
            .generatedFiles();

        String actual = Joiner.on("\n")
            .join(Files.readLines(file, Charset.forName("UTF-8")))
            .trim();
        String expected = buildExpectedGeneratedFile();
        assertThat(actual).isEqualTo(expected);
        file.delete();
    }

    @NotNull
    private JavaFileObject getSourceObject() {
        @Language("java")
        String source = "package test;\n" +
            "\n" +
            "import com.importre.kotlin.enumerize.EnumExt;\n" +
            "\n" +
            "class Log {\n" +
            "    \n" +
            "    @EnumExt\n" +
            "    private Level level;\n" +
            "\n" +
            "    enum Level {\n" +
            "        DEBUG,\n" +
            "        ERROR,\n" +
            "    }\n" +
            "}\n";

        return JavaFileObjects
            .forSourceString("test.Log", source);
    }

    @NotNull
    private String buildExpectedGeneratedFile() {
        return FileSpec
            .builder("test", "LogLevel")
            .addComment("Generated by kotlin-enumerize")
            .addAnnotation(
                AnnotationSpec.builder(JvmName.class)
                    .addMember("%S", "LogExt")
                    .build()
            )
            .addProperty(
                PropertySpec
                    .builder("isDebug", TypeNames.BOOLEAN)
                    .receiver(TypeVariableName.get("Log"))
                    .getter(
                        FunSpec.getterBuilder()
                            .addStatement("return Log.Level.DEBUG == level")
                            .build()
                    )
                    .build()
            )
            .addProperty(
                PropertySpec
                    .builder("isError", TypeNames.BOOLEAN)
                    .receiver(TypeVariableName.get("Log"))
                    .getter(
                        FunSpec.getterBuilder()
                            .addStatement("return Log.Level.ERROR == level")
                            .build()
                    )
                    .build()
            )
            .build()
            .toString()
            .trim();
    }
}
